version: '3'
services:
  web:
    build: ./
    container_name: blog
    restart: always
    volumes:
      - ./blog/:/var/www/html
    ports:
      - "8084:80"
    environment:
      - NAME_SERVER=example.com
      - HTTPS=false
      - MYSQL_DATABASE=blog
      - MYSQL_USER=myuserdb
      - MYSQL_PASSWORD=mypassworddb
    depends_on:
      - db
  db:
    image: mysql
    container_name: blogdb
    restart: always
    volumes:
      - ./db/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=myrootpassword
      - MYSQL_DATABASE=blog
      - MYSQL_USER=myuserdb
      - MYSQL_PASSWORD=mypassworddb
