version: '3'
services:
  traefik:
    image: traefik:v2.2
    container_name: traefik
    command: 
      - "--api.insecure=true"
      - "--providers.docker.exposedbydefault=true"
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--providers.file.filename=/dynamic.yaml" # <== Referring to a dynamic configuration file
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true" # <== Enable TLS-ALPN-01 to generate and renew ACME certs
      - "--certificatesresolvers.mytlschallenge.acme.email=example@email.com" # <== Setting email for certs
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
      - ./dynamic.yaml:/dynamic.yaml
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.port=8085"
    networks:
      - web

networks:
  web:
    external: true

